spring:
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      add-mappings: true
      static-locations: classpath:/static/

server:
  port : 8080

execution:
  docker:
    python-image: python:3.11-alpine
    java-image: eclipse-temurin:17-jdk
